### ISSUE TITLE
demo dosen't have any text 

### ISSUE THREAD

**Issue by StanleyYake** [PickNikRobotics/rviz_visual_tools#96]
Hello there, I'm on ROS Kinetics and build your file successfully, but when I run below command
`roslaunch rviz_visual_tools demo_rviz.launch`
`roslaunch rviz_visual_tools demo.launch`
there is a warning :[ WARN] [1537511480.627642188]: Marker 'Text/27' contains unnormalized quaternions. This warning will only be output once but may be true for others; enable DEBUG messages for ros.rviz.quaternions to see more details.

and RVIZ have the elements in it but text display is not shown.
![qq 20180921143810](https://user-images.githubusercontent.com/7522853/45864306-2ce48b00-bdac-11e8-9de7-b7349d1c0606.png)

**Comment by VictorLamoine** [comment]
What version of `rviz_visual_tools` are you using?
Text works on my machine with the latest version (504585f1fd90b3f697abdad807d877a164c1a4f1) but I do get the warning about quaternions.

See https://github.com/PickNikRobotics/rviz_visual_tools/pull/110 if you want to test with the latest version, some renaming has to be done otherwise the demo files won't work.

https://github.com/PickNikRobotics/rviz_visual_tools/pull/111 fixes the warning.
